// <auto-generated />
namespace AcademicJournal.BLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class assignment_model_FileName_field_added_Description_removed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(assignment_model_FileName_field_added_Description_removed));
        
        string IMigrationMetadata.Id
        {
            get { return "201712261002102_assignment_model_FileName_field_added_Description_removed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
