// <auto-generated />
namespace AcademicJournal.BLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class submissionmodeladdedtestmodeldeletedassignmentmodelchangedassignmentfileandsubmitfilemodeladded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(submissionmodeladdedtestmodeldeletedassignmentmodelchangedassignmentfileandsubmitfilemodeladded));
        
        string IMigrationMetadata.Id
        {
            get { return "201801101517261_submission model added, test model deleted, assignment model changed, assignment-file and submit-file model added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
