// <auto-generated />
namespace AcademicJournal.BLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SubmissionIdpropaddedtoSubmitFilemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SubmissionIdpropaddedtoSubmitFilemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201801151002420_SubmissionId prop added to SubmitFile model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
