// <auto-generated />
namespace AcademicJournal.BLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class removedtestmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedtestmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201801110342599_removed-test-model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
