// <auto-generated />
namespace AcademicJournal.BLL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class JournalworDayrelationshipfixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JournalworDayrelationshipfixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201801040944577_Journal worDay relationship fixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
